### ISSUE TITLE
[BUG] Error in v10 when loading with libwrapper

### ISSUE THREAD

**Issue by Truncated** [dmrickey/ckl-advanced-templates-pf1#20]
**Module Version:** v1.3.4

**Describe the bug**
When loading a world with the module enabled and libwrapper a red error banner appears along the top. Console error entry shown in Screenshots.

**To Reproduce**
1. Load with modules

**Expected behavior**
No errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/14208325/202571653-a64abd43-8627-4402-925d-274c0be86271.png)
![image](https://user-images.githubusercontent.com/14208325/202571679-9504b624-721f-43c6-9177-6c3c8722db16.png)
![image](https://user-images.githubusercontent.com/14208325/202571754-2141df4b-eb47-4701-8ff2-903cae4eb89d.png)

**Browser:**
 - Chrome

**Foundry Version:** 
- v10.290

**Game System:** 
PF1e v0.82.2

**Additional context**
Looks like this is a combo of libwrapper and PF1 depreciated warnings.

**Comment by dmrickey** [comment]
Sorry for the late response. This module hasn't been updated for v10. There's more than just this that's broken. I'm slowly updating this for v10, but unfortunately my priority for it is very low as my Pathfinder game finished just before v10 released.

**Comment by dmrickey** [comment]
This will be fixed in the next release
