### ISSUE TITLE
[BUG] Incompatibility with Perfect Vision's sight limit

### ISSUE THREAD

**Issue by lyka473** [dmrickey/ckl-advanced-templates-pf1#22]
**Module Version:** v1.4.0

**Describe the bug**
This module prevents the sight limit of Perfect Vision from functioning as intended

**To Reproduce**
1. Install both Advanced Templates and Perfect Vision
2. Place down a template
3. Within the template configuration, Click on Configure Vision Limitation and set to desired distance (e.g. 5ft)
4. Place token within the template and select them to see what they can see

**Expected behavior**
The token's vision should be impacted by the Configure Vision Limitation setting from Perfect Vision.

**Screenshots**
Without module enabled:

![Foundry_Virtual_Tabletop_5B1RDSVpUE](https://user-images.githubusercontent.com/88289231/213947463-cd112f24-6a3d-4e24-82e9-1400e8102c2a.jpg)

With module enabled:

![Foundry_Virtual_Tabletop_QChNcRDaq2](https://user-images.githubusercontent.com/88289231/213947361-64595e12-ce0f-4ccd-be67-4a96aacae480.jpg)

**Browser:**
 Foundry Client/Firefox

**Foundry Version:** 
10.291

**Game System:** 
0.82.5

**Additional context**
N/A

**Comment by dmrickey** [comment]
Interesting. I'll install that mod and see if I can figure out what's going on

**Comment by dmrickey** [comment]
Sorry for the late response, but as Perfect Vision is no longer supported for Foundry, and this mod has been updated for v11, there basically is no longer an incompatibility for a mod that doesn't exist for the current version.
