### ISSUE TITLE
Override Texture not functional while using rectangular template

### ISSUE THREAD

**Issue by Motara7** [dmrickey/ckl-advanced-templates-pf1#25]
**Module Version:** v1.4.1

**Describe the bug**
When using the Override Texture option for a rectangular template, the desired texture appears during placement, but as soon as I click to finalize the placement of the template, the texture vanishes and I am left with just the colored template. Override texture on other template shapes seems to work just fine.

**To Reproduce**
1. Edit a spell and go to the Miscellaneous tab.
2. Select Rectangle from the Template Type drop down.
3. Enter 10 for Size
4. Check the Override Texture box. Then select a custom template.
5. Cast the spell and place the template.
6. See the texture while moving the template, but witness the texture disappear once placed.

**Expected behavior**
The texture should remain once the template is placed.

**Screenshots**
Pre-placement and post-placement screenshots included.

![Pre-placement](https://user-images.githubusercontent.com/74425292/216455671-e98def34-8e22-4213-8cba-58702b71578e.jpg)
![Post-placement](https://user-images.githubusercontent.com/74425292/216455676-bb1fbd9b-e444-47b0-8cd4-9fce17971ccd.jpg)

**Browser:**
 - Chrome

**Foundry Version:** 
V10, Build 291

**Game System:** 
Pathfinder 1 0.82.5

**Additional context**
No errors or warnings appear in the console.

**Comment by dmrickey** [comment]
Interesting. My mod shouldn't be interacting with cone and circle templates. I'll take a look to see what I overlooked.

**Comment by dmrickey** [comment]
Fixed in 1.4.2
