### ISSUE TITLE
Templates not adding targets to the chat card for the spell effect.

### ISSUE THREAD

**Issue by madcatprimary** [dmrickey/ckl-advanced-templates-pf1#38]
**Module Version:** v2.2.1

**Describe the bug**
With Advanced Templates enabled, targets selected by template do not appear in the chat card for the spell effect. I've used Find the Culprit, and with it narrowed down to only Advanced Templates and libraries still enabled, no targets are displayed. They appear to get highlighted during the cast, and then untargeted before the chat card can display. 

**To Reproduce**
1. Go to spells on a character with spells enabled.
2. Cast a spell or feature that has a template designated in the Action. Targeting Method does not seem to matter.
3. Observe template's targets when placing template, they will be marked with the four arrows in the corners of the tokens, as expected.
4. Once the template is placed, the targeting effect will end, and the chat card will be generated without any tokens listed in it. 

**Expected behavior**
All targets in the area of the template should appear in the chat card. 

**Screenshots**
![image](https://github.com/dmrickey/ckl-advanced-templates-pf1/assets/67210079/b4899a0d-77b3-498c-ade6-11369909ef16)

**Browser: Testing as GM, in App, no browser tested.**
 - 

**Foundry Version: 11.315** 

**Game System: pf1e** 

**Additional context**
Screenshot shows what mods are still enabled.

**Comment by dmrickey** [comment]
Fixed in 2.2.2
